# TODO: remove this file later. Presently a workaround for building docs in readthedocs for python 3.5

name: py35
dependencies:
- python=3.5
- pip
- PyYAML
- ujson
- pip:
  - protobuf
  - mapbox-vector-tile
  - mercantile
  - asyncpg
  - aiohttp
  - aiohttp_cors
  - cchardet