buffer: 128
layers:
- name: 'roads'
  clip: true
  queries:
    - minzoom: 12
      maxzoom: 20
      sql: |
        -SELECT
          way,
          highway,
          name,
          railway,
          mz_id AS __id__,
          mz_road_sort_key AS sort_key,
          (CASE WHEN highway IN ('motorway', 'motorway_link') THEN 'highway'
                WHEN highway IN ('trunk', 'trunk_link', 'secondary', 'primary') THEN 'major_road'
                ELSE 'minor_road' END) AS kind,
          (CASE WHEN highway LIKE '%_link' THEN 'yes'
                ELSE 'no' END) AS is_link,
          (CASE WHEN tunnel IN ('yes', 'true') THEN 'yes'
                ELSE 'no' END) AS is_tunnel,
          (CASE WHEN bridge IN ('yes', 'true') THEN 'yes'
                ELSE 'no' END) AS is_bridge
        FROM
          planet_osm_line
        WHERE
            mz_road_level <= 12
        ORDER BY
          sort_key ASC
- name: 'places'
  queries:
    - minzoom: 8
      maxzoom: 13
      sql: |
        -SELECT
            name,
            place AS kind,
            way,
            mz_id AS __id__
        FROM
          planet_osm_point
        WHERE
          name IS NOT NULL
          AND place IN (
            'city',
            'county',
            'province',
            'island',
            'town',
            'neighbourhood',
            'suburb',
            'locality',
            'lake',
            'village',
            'hamlet',
            'isolated_dwelling'
        )
        ORDER BY __id__ ASC
