# example docker-compose file for two-core setup
# ideally, setup one container per core
# see nginx config for configuration of caching

version: '2'

services:

  aiovt_app_1:  # must correspond to your server names in nginx.conf
    restart: always
    image: shongololo/aiovectortiler:latest
    expose:
    - 80  # must correspond to your port number in nginx.conf
    volumes:
    - .:/configs  # for loading the server configs and layer_recipes folder
    networks:
    - aiovt_network

  aiovt_app_2:
    restart: always
    image: shongololo/aiovectortiler:latest
    expose:
     - 80
    volumes:
     - .:/configs
    networks:
    - aiovt_network

  nginx:
    restart: always
    image: nginx
    ports:
    - 8080:8080 # map your exterior port to nginx config's listening port
    volumes:
    - .:/etc/nginx # for loading the nginx.conf file from your configs folder
    networks:
    - aiovt_network
    depends_on:
    - aiovt_app_1
    - aiovt_app_2
    links:
    - aiovt_app_1
    - aiovt_app_2

networks:
  aiovt_network:
